### ISSUE TITLE
text not visible

### ISSUE THREAD

**Issue by Not-Sarthak** [EddieHubCommunity/good-first-issue-finder#348] opened 2023-06-07 08:55 UTC
### Description

In the dark mode, the ui text is set to light in the filters section which makes the text unreadable as it matches up with the background color.

### Screenshots

![image](https://github.com/EddieHubCommunity/good-first-issue-finder/assets/92942966/54d37bca-1757-4454-9a87-db3bb77f9656)

**Comment by Cahllagerfeld** [comment] 2023-06-07 09:09
nice catch! 
I'm closing it as a duplicate of #342

**Closed by Cahllagerfeld** 2023-06-07 09:09 UTC
Labels: 🛠 goal: fix
