### ISSUE TITLE
[OTHER] Improve animation color of github of techstack in dark mode

### ISSUE THREAD

**Issue by MahirMahdi** [EddieHubCommunity/good-first-issue-finder#315] opened 2023-03-20 09:58 UTC
### What would you like to share?

It would look better if the animation color is changed from black to white in dark mode.

![Screenshot 2023-03-20 155605](https://user-images.githubusercontent.com/66949598/226305872-5d74d566-f48c-4ccd-ab05-7cedb806f465.png)

**Comment by Srinja333** [comment] 2023-03-20 18:57
Can I work on this?

**Comment by Cahllagerfeld** [comment] 2023-03-20 18:58
sure 👍

**Comment by Srinja333** [comment] 2023-03-30 09:28
@Cahllagerfeld  please check it out

**Comment by Poonam1607** [comment] 2023-04-01 04:21
It's still showing the black color in dark mode @Srinja333

**Comment by abdullah43577** [comment] 2023-04-14 07:38
@MahirMahdi  I would like to know if this issue is fixed or if I should work on the fix

**Comment by MahirMahdi** [comment] 2023-04-14 17:09
> @MahirMahdi I would like to know if this issue is fixed or if I should work on the fix

Ig someone has made a PR on it. But it's not merged yet.

**Comment by abdullah43577** [comment] 2023-04-15 05:27
> > @MahirMahdi I would like to know if this issue is fixed or if I should work on the fix
> 
> Ig someone has made a PR on it. But it's not merged yet.

ok

**Comment by anubhav1206** [comment] 2023-04-18 19:34
Can I work on this

**Comment by Cahllagerfeld** [comment] 2023-04-19 12:32
its opened with #316 alreay 👍

**Comment by Rajeevjewar** [comment] 2023-04-24 08:07
> ### What would you like to share?
> It would look better if the animation color is changed from black to white in dark mode.
> 
> ![Screenshot 2023-03-20 155605](https://user-images.githubusercontent.com/66949598/226305872-5d74d566-f48c-4ccd-ab05-7cedb806f465.png)
> 
> ### Additional information
> _No response_

Yeah Exactly because It doesn't show a good visual hierarchy it should good idea to change the dark color to light version of its body background color;
we can use try these two colors:
#e9e9ea 
#d3d4d5
both colors are the tint versions of the main color

**Comment by rahul0x00** [comment] 2023-07-02 10:53
@Cahllagerfeld Hi,is it still open?

**Comment by Cahllagerfeld** [comment] 2023-07-02 14:54
Yep, as there hasn't been any activity here, I'll assign it to you 👍

**Comment by rahul0x00** [comment] 2023-07-02 14:59
Should i change the contrast or make it dynamic like white in dark mode and black in light mode,in my opinion the former makes more sense

**Comment by Cahllagerfeld** [comment] 2023-07-02 15:15
exactly, that's the intended behavior. I think for light mode its fine already, it only requires the adjustment for dark mode 👍

**Comment by rahul0x00** [comment] 2023-07-05 14:34
Hi, @Cahllagerfeld I've addressed the issue, please take a look at the PR, and let me know if any further modifications or adjustments are required

**Closed** 2023-07-12 09:46 UTC
Labels: 🚦 status: awaiting triage
