### ISSUE TITLE
[FEATURE] <Filter By Language Feature>

### ISSUE THREAD

**Issue by codad5** [EddieHubCommunity/good-first-issue-finder#359] opened 2023-06-23 03:21 UTC
### Description

I think having a feature to filter your language of choice would be good as it makes searching for the right project to work on easier.

**Comment by Cahllagerfeld** [comment] 2023-06-23 06:54
Thanks for raising the issue 👍 

I'm going to close this as a duplicate of #77 though, as we're having an issue for this already 👍

**Closed by Cahllagerfeld** 2023-06-23 06:54 UTC
Labels: ✨ goal: improvement
