### ISSUE TITLE
[OTHER] Change animation color for github section to make it contrasty

### ISSUE THREAD

**Issue by rkscodes** [EddieHubCommunity/good-first-issue-finder#346] opened 2023-06-05 09:55 UTC
### What would you like to share?

<img width="369" alt="Screenshot 2023-06-05 at 3 14 57 PM" src="https://github.com/EddieHubCommunity/good-first-issue-finder/assets/30290728/42993c9a-22a9-48a3-89a7-c69e656c87f3">

It doesn't have enough contrast, maybe using some other color will be great in here.

**Comment by Cahllagerfeld** [comment] 2023-06-05 14:15
Thanks for raising it. 👍 

I'm closing it as a duplicate of #315

**Closed by Cahllagerfeld** 2023-06-05 14:15 UTC
Labels: 🚦 status: awaiting triage
